### ISSUE TITLE
Resource preview is missing in some cases

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#22]
The problem occurs in some datasets where resources are not available. Below a sample resource's URL to use to replicate the problem:

http://dati.retecivica.bz.it/it/dataset/italian-pollnet-webservices/resource/1db34ff4-c3df-4d04-a6ec-570b4a89772d#

The related error message is:
Could not load view: DataProxy returned an error (Request Error: Backend did not respond after 10 seconds)

**Comment by tdipisa** [comment]
can this issue be replicated locally?

**Comment by cezio** [comment]
I don't think so. AFAIR, this relies on external service that generates preview, so resource needs to be available from internet. If you're running it locally, this will return address resolution error. If I remember correctly, datastore/datapusher solves this (because data will be visualized locally).

**Comment by tdipisa** [comment]
@cezio, ok but I think we can try to replicate the issue in [demo server](http://188.165.62.180/) importing the same resource

**Comment by cezio** [comment]
I've added test resource to http://188.165.62.180/dataset/test-dataset/resource/bc695280-b56c-4d30-95da-9b6f515d08f0#

There was a datapusher/datastore installed, so i had to disable datapusher for a moment to replicate it.

It seems the problem is jsondataproxy service takes some time to process the xlsx file, more than nominal 10 seconds. Url used (which is canceled by browser)
http://jsonpdataproxy.appspot.com/?callback=jQuery17107331894830883685_1518001736958&url=http%3A%2F%2Fdati.retecivica.bz.it%2Fservices%2FPOLLNET_YEAR_REP%3Fformat%3Dxlsx%26STAT_ID%3D1%26from%3D2016-01-01&max-results=1000&type=XLSX&_=1518001739586
